version: '3.8'
#name: mysql_vlog

services:
  db:
    #build: ./mySQL
    image: 975050258788.dkr.ecr.us-east-2.amazonaws.com/awscondocker:mysql_vlog-db-latest
    environment:
      MYSQL_DATABASE: vlog_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: vlog_user
      MYSQL_PASSWORD: vlog_password
    ports:
      - "13027:3306"
    volumes:
      - "db_data:/var/lib/mysql"

  api:
    #build: ../api_docker
    image: 975050258788.dkr.ecr.us-east-2.amazonaws.com/awscondocker:mysql_vlog-api-latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=vlog_user
      - DB_NAME=vlog_db
      - DB_PASSWORD=vlog_password
    depends_on:
      - db

volumes:
  db_data: 
    driver: "local"
