CREATE DATABASE IF NOT EXISTS vlog_db;
USE vlog_db;

CREATE USER IF NOT EXISTS 'vlog_user'@'%' IDENTIFIED BY 'vlog_password';
GRANT ALL PRIVILEGES ON vlog_db.* TO 'vlog_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS vlog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    picture TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  isAdmin TINYINT(1) NOT NULL DEFAULT 1
);
